spring:
  application:
    name: gongdori-lab-backend

  datasource:
    url: jdbc:mysql://${MYSQL_HOST}/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false

#  flyway:
#    enabled: true
#    baseline-on-migrate: true
#    locations: classpath:db/migration

# 각종 설정값 .donenv 대체

AES_KEY: ${AES_KEY}