spring:
  application:
    name: gongdori-lab-backend

  datasource:
    url: jdbc:mysql://${MYSQL_HOST}/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

#  flyway:
#    enabled: true
#    baseline-on-migrate: true
#    locations: classpath:db/migration